esphome:
  name: knob_kitchen
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "knob_kitchen Fallback Hotspot"
    password: !secret fallback_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass
    
    
binary_sensor:
  - platform: gpio
    id: button_kitchen
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - homeassistant.service:
            service: media_player.media_next_track
            data:
              entity_id: media_player.spotify
        - logger.log: "double click - next track"
    - timing:
      - ON for .5s to 2s
      - OFF for at least 0.1s
      then:
        - script.execute: start_playlist_shuffle
        - logger.log: "long press - play spotify playlist"
    - timing:
      - ON for at most .49s
      - OFF for at least 0.25s
      then:
        - homeassistant.service:
            service: media_player.media_play_pause
            data:
              entity_id: media_player.spotify
        - logger.log: "single click - play/pause"

sensor:
  - platform: rotary_encoder
    id: knob_kitchen
    pin_a: D4
    pin_b: D3
    min_value: -2
    max_value: 2
    resolution: 1
    filters:
      - or:
        - debounce: 0.1s
        - delta: 10
    on_value_range:
      - above: 1
        then:
          - script.execute: volume_up
      - below: -1
        then:
          - script.execute: volume_down
              
script:
  - id: volume_up
    then:
      - homeassistant.service:
          service: media_player.volume_up
          data:
            entity_id: media_player.kitchen_speakers
      - logger.log: "vol up trigger"
      - sensor.rotary_encoder.set_value:
          id: knob_kitchen
          value: 0
  - id: volume_down
    then:
      - homeassistant.service:
          service: media_player.volume_down
          data:
            entity_id: media_player.kitchen_speakers
      - logger.log: "vol down trigger"
      - sensor.rotary_encoder.set_value:
          id: knob_kitchen
          value: 0
  - id: start_playlist_shuffle
    then:
      - homeassistant.service:
          service: media_player.play_media
          data:
            entity_id: media_player.spotify
            media_content_id: spotify:playlist:7qFH2xh3ZiewF1WDgXQbfC
            media_content_type: playlist
      - homeassistant.service:
          service: media_player.shuffle_set
          data:
            entity_id: media_player.spotify
            shuffle: "true"
      - homeassistant.service:
          service: media_player.media_next_track
          data:
            entity_id: media_player.spotify
